### ISSUE TITLE
Updating from 3.x to 4.x

### ISSUE THREAD

**Issue by thyco** [iamguid/ngx-mf#14]
Hello,

We're trying to update from 3.x to 4.x and as noted in the 4.0 release notes, the infer modes are removed.
It states : 
InferModes has been removed - now fields optionality and nullability will be inferred from model and all form controls are required in inferred form type.

My question is: what does "now fields optionality and nullability will be inferred from model" mean? We use "?" in our model for optional fields, but this does not seem to work anymore.

How are we supposed to have optional fields now or is this no longer possible?

Thanks in advance.

**Comment by iamguid** [comment]
Hello, @thyco, thank you for your question.

That means, if you use optional in field, it will be inferred as `T | undefined` in result type, but it will be required in form type. If you want to exclude it from form type you should Omit/Pick fields, that you want to remove/add from/to form type completely. Or you should define your form including that field and initialize Form(Control/Group/Array) with undefined by default, e.g. `new FormControl(undefined)`, and then you will be able to get `values` with `undefined` feields from form.

I removed infer modes, because it was hard to explain how it works, and in main case it didn't make sense. About optional behavior i would say that if you define your model, you should always define FormControl for optional fields, because otherwise it wouldn't work in angular-froms. You always need to define all fields as Form(Control/Group/Array), even you define it as optional it is how angular-forms works.

If you have some ideas how it should be, please, give me your use cases and I'll try to help you. Maybe the behavior of the library is not clear, but anyway, we can change it.

Thank you!

**Comment by iamguid** [comment]
Hello, @thyco, thank you for your question

I think it is a bug, because if you define model as optional, it should be optional in inferred type too, so I'll fix it in next release.

Thank you!
