### ISSUE TITLE
Use a union doesn't work as expected

### ISSUE THREAD

**Issue by ArielGueta** [iamguid/ngx-mf#2]
I have the following type:

```ts
interface Foo {
  a: {
    b: { type: 'a', keyA: string } | { type: 'b', keyB: string }
  }
}

type Form = FormModel<Foo, { a: { b: 'group' } }, InferModeRequired & InferModeNonNullable>['controls']
```

And the following code throws:

```ts
builder.nonNullable.group<Form>({
    a: builder.nonNullable.group({
      b: builder.nonNullable.group({
        type: builder.nonNullable.control('a' as const),
        keyA: builder.nonNullable.control('')
      })
    })
  })
```

The code should work as one of the union types is define.

**Comment by iamguid** [comment]
Thank you for creating new issue, i will check now.

**Comment by iamguid** [comment]
So the main problem - I can't traverse by union type using typescript, because it is typescript limitation. Here is [example](https://www.typescriptlang.org/play?#code/C4TwDgpgBMEM7AIxQLxQN5QNYRAQQC4oByAQ2KgF8oAfDbXAISOICNjKBuAWACg-QkGPGAAmVBj5QoAbRwgoASwB2DEAHsAZsISIAukVi65uPT16U+A8NABO8AK4AbYBKNiZxeXmJmgA), that it won't work.

But you can workaround this limitation, you have choice:

1) Divide your interface by two, like 
```typescript
interface FooBA {
  type: 'a';
  keyA: string;
}

interface FooBB {
  type: 'b';
  keyB: string;
}

interface Foo1 {
  a: {
    b: FooBA
  }
}

interface Foo2 {
  a: {
    b: FooBB
  }
}
```
And then construct your concrete form using concrete interface...

2) Use `Replace` to infer what you need, for example see https://github.com/iamguid/ngx-mf/blob/master/examples/example3.ts#L21 also see docs https://github.com/iamguid/ngx-mf#annotations

Ask questions if something is not clear 🌚

**Comment by ArielGueta** [comment]
Thanks for the quick response. It still not work for me. Can you please show a quick demo on stackblitz?

**Comment by iamguid** [comment]
Shure, for example https://stackblitz.com/edit/angular-ngx-mf-wvaqo5?file=src%2Fapp%2Fapp.component.ts
