### ISSUE TITLE
Optional controls

### ISSUE THREAD

**Issue by DostalTomas** [iamguid/ngx-mf#9]
Hi, 
  Thank You for this great tool. It simplifies working with ng-forms very well.

   But I have a problem defining optional form fields. See example.
   Is it possible to do this in some different way?

```
import {FormModel, FormElementGroup} from 'ngx-mf';
import {FormGroup, FormControl} from '@angular/forms'

interface Contact {
  address: string;
  phone: string;
}

interface Person {
  name: string;
  contact?: Contact; // <==
}

type PersonForm = FormModel<Person, {
  contact: FormElementGroup
}>;

type ContactForm = FormModel<Contact>;

const contactForm = new FormGroup<ContactForm['controls']>({
  address: new FormControl('addr', {nonNullable: true}),
  phone: new FormControl('123456789', {nonNullable: true})
});

const form = new FormGroup<PersonForm['controls']>({
  name: new FormControl('John Doe', {nonNullable: true}),
  // contact has to be specified, or TS error, but it has side effects in creating form
  // contact: null as unknown as ContactForm // FIXME
});

const condition = true;
if (condition) {
  form.addControl('contact', contactForm);
}
```

Thank You,
   Tomas

**Comment by iamguid** [comment]
Hello, sorry for the late response, and thank you for open issue.

Currently optional fields are required in form, optional field means that field is nullable but you steel should define it.

Can you describe your case in more detail, because if you don't use that field you can just omit it from your model, like Omit<Model, "field">.

About condition in example that you sent, is it really what you want? You can hide just a control from ui or just disable or enable field based on condition
